"""analysis artifact access

Splits the cross-tenant analysis cache (Gate 1 Step 10): the RESULT stays
shared by content_hash, the right to fetch its keyframe strips does not.

Two data steps beyond the schema, both aimed at not breaking a deployment
that already has analyses (the failure mode Step 2 shipped and §2.3 of the
handoff records):

- ``analysis_id`` is recovered from each payload's own ``keyframes`` entry.
  Strips are named ``{analysis_id}_overview.png``, so the id is recoverable
  from data already stored; without this every pre-existing strip would 404
  the moment the ownership check goes live.
- ``analysis_access`` is seeded for the bootstrap account — the lowest-id
  ACTIVE user, the same tenant Step 7 attributed pre-ownership projects to.
  Everything analysed before this revision was analysed when there was
  effectively one tenant, and that is the one.

Revision ID: c3959889aab8
Revises: 81e1445feaa6
Create Date: 2026-07-21 17:55:47.070846

"""
from pathlib import PurePosixPath
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3959889aab8'
down_revision: Union[str, Sequence[str], None] = '81e1445feaa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'content_hash', name='uq_analysis_access_user_hash')
    )
    op.create_index(op.f('ix_analysis_access_content_hash'), 'analysis_access', ['content_hash'], unique=False)
    op.create_index(op.f('ix_analysis_access_user_id'), 'analysis_access', ['user_id'], unique=False)
    op.add_column('media_analyses', sa.Column('analysis_id', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_media_analyses_analysis_id'), 'media_analyses', ['analysis_id'], unique=False)
    # ### end Alembic commands ###
    _backfill_analysis_ids()
    _seed_bootstrap_access()


def _backfill_analysis_ids() -> None:
    """Recover ``analysis_id`` for rows written before this revision.

    The payload already names the strips (``keyframes``), and every strip of
    one analysis shares the ``{analysis_id}_`` prefix, so the id is derivable
    from stored data rather than lost. Entries may be full
    ``/ui/media/analysis/x_overview.png`` URLs (the pre-Step-10 format) or
    bare basenames, so both are reduced to a basename first.

    Deliberately tolerant, one row at a time: a payload with no usable
    keyframe leaves ``analysis_id`` NULL and that analysis's strips 404 until
    it is recomputed. Failing the whole migration over one malformed JSON blob
    would be far worse — it would block the upgrade of the entire deployment.
    """
    bind = op.get_bind()
    rows = bind.execute(
        sa.text("SELECT id, data FROM media_analyses")
    ).fetchall()
    for row_id, data in rows:
        analysis_id = _analysis_id_from_payload(data)
        if analysis_id is None:
            continue
        bind.execute(
            sa.text("UPDATE media_analyses SET analysis_id = :aid WHERE id = :rid"),
            {"aid": analysis_id, "rid": row_id},
        )


def _analysis_id_from_payload(data) -> str | None:
    """``{analysis_id}`` from the first usable ``keyframes`` entry, or None."""
    import json

    if isinstance(data, (str, bytes)):
        try:
            data = json.loads(data)
        except (ValueError, TypeError):
            return None
    if not isinstance(data, dict):
        return None
    keyframes = data.get("keyframes")
    if not isinstance(keyframes, list):
        return None
    for entry in keyframes:
        if not isinstance(entry, str) or not entry:
            continue
        name = PurePosixPath(entry).name
        head = name.split("_", 1)[0]
        if head:
            return head
    return None


def _seed_bootstrap_access() -> None:
    """Grant the bootstrap account access to every already-stored analysis.

    Same tenant Step 7 chose for pre-ownership projects: the lowest-id ACTIVE
    user, because on a real deployment the operator's own account was created
    first and must keep reading its own data. No users (a fresh install) means
    nothing to grant and nothing to break.
    """
    bind = op.get_bind()
    owner = bind.execute(
        sa.text("SELECT id FROM users WHERE status = 'active' ORDER BY id LIMIT 1")
    ).scalar()
    if owner is None:
        return
    bind.execute(
        sa.text(
            "INSERT INTO analysis_access (user_id, content_hash) "
            "SELECT :owner, content_hash FROM media_analyses"
        ),
        {"owner": owner},
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_analyses_analysis_id'), table_name='media_analyses')
    op.drop_column('media_analyses', 'analysis_id')
    op.drop_index(op.f('ix_analysis_access_user_id'), table_name='analysis_access')
    op.drop_index(op.f('ix_analysis_access_content_hash'), table_name='analysis_access')
    op.drop_table('analysis_access')
    # ### end Alembic commands ###
