"""accounts: users and api_tokens tables

Gate 1 Step 3: schema and token-minting only — no request on ``/api`` or
``/mcp`` checks anything against these tables yet (that wiring is Gate 1
Steps 4-6). Purely additive: neither of the four existing tables
(``projects``, ``operations``, ``annotations``, ``media_analyses``) is
touched.

``users`` stores an argon2id ``password_hash``, never a plaintext password
(see ``app.db.repositories.users``). ``api_tokens.token_hash`` stores a
SHA-256 digest of a minted opaque token
(``secrets.token_urlsafe(32)``, see ``app.db.repositories.tokens``) — the
plaintext itself is never persisted anywhere, only shown to the caller once
at mint time. ``api_tokens.user_id`` is a real foreign key to ``users.id``,
unlike ``operations.project_id``/``annotations.project_id``, which are
plain string references by design (see ``app/db/models.py``) — an
orphaned token is a bug, not a valid state, so the FK is enforced here.

Generated via ``alembic revision --autogenerate`` against a database
already at the ``5ed7cccf2291`` baseline; reviewed by hand against
``app/db/models.py`` before being committed, same process as the baseline
revision itself.

Revision ID: d461a3e6aaad
Revises: 5ed7cccf2291
Create Date: 2026-07-21 11:04:35.798030

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd461a3e6aaad'
down_revision: Union[str, Sequence[str], None] = '5ed7cccf2291'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_tokens_token_hash'), 'api_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_api_tokens_user_id'), 'api_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_tokens_user_id'), table_name='api_tokens')
    op.drop_index(op.f('ix_api_tokens_token_hash'), table_name='api_tokens')
    op.drop_table('api_tokens')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
